source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '~> 5.2.3'
gem 'mysql2', '>= 0.5.3', '< 0.6.0' 
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'
gem 'httparty'
gem 'bulk_insert', '~> 1.8', '>= 1.8.1'

gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'haml-rails'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'gon'
gem 'settingslogic'
gem 'cancancan'
gem 'bugsnag'
gem 'rack-ssl-enforcer'
gem 'carrierwave', '~> 2.0'
gem 'fog'
gem 'parallel'
gem 'smarter_csv'
gem "aws-sdk-s3", require: false
gem 'dalli'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails'
  gem 'pry', '~> 0.12.2'
  gem 'pry-rails'
  gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
  gem 'rails-controller-testing'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-sidekiq'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'devise'
gem 'omniauth-google-oauth2'
gem "redis", "~> 4.0"
source "https://f2ec81aa:cbedd6bc@gems.contribsys.com/" do
  gem 'sidekiq-pro'
end
gem 'sidekiq-failures'
gem 'sidekiq-cron'
gem 'sidekiq'
gem 'rest-client'

gem 'lograge'
gem 'logstash-event'
gem 'ohm'
gem 'ohm-contrib'